image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build

build:latest:
  stage: build
  script:
    - docker build -t ${DOCKERHUB_REPO}:latest .
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}; fi
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker push ${DOCKERHUB_REPO}:latest; fi

build:git:
  stage: build
  script:
    - docker build --build-arg CADDY_FEATURES=http.git --build-arg APK_PACKAGES=git -t ${DOCKERHUB_REPO}:git .
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}; fi
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker push ${DOCKERHUB_REPO}:git; fi
