image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build
  - dockerpush

build:latest:
  stage: build
  only:
    - branches@eownis/docker-caddy
  except:
    - master@eownis/docker-caddy
  script:
    - docker build .

build:git:
  stage: build
  only:
    - branches@eownis/docker-caddy
  except:
    - master@eownis/docker-caddy
  script:
    - docker build --build-arg CADDY_FEATURES=git --build-arg APK_PACKAGES=git .

dockerpush:latest:
  stage: dockerpush
  only:
    - master@eownis/docker-caddy
  script:
    - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
    - docker build -t ${DOCKERHUB_REPO}:latest .
    - docker push ${DOCKERHUB_REPO}:latest

dockerpush:git:
  stage: dockerpush
  only:
    - master@eownis/docker-caddy
  script:
    - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
    - docker build --build-arg CADDY_FEATURES=git --build-arg APK_PACKAGES=git -t ${DOCKERHUB_REPO}:git .
    - docker push ${DOCKERHUB_REPO}:git
